name: insanet
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.05.30=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1u=h7f8727e_0
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.16=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - charset-normalizer==3.2.0
      - cycler==0.11.0
      - fonttools==4.38.0
      - idna==3.4
      - kiwisolver==1.4.4
      - matplotlib==3.5.3
      - numpy==1.21.6
      - opencv-python==4.8.0.74
      - packaging==23.1
      - pillow==9.5.0
      - pyparsing==3.1.0
      - python-dateutil==2.8.2
      - requests==2.31.0
      - scipy==1.7.3
      - six==1.16.0
      - torch==1.11.0
      - torchaudio==0.11.0
      - torchvision==0.12.0
      - typing-extensions==4.7.1
      - urllib3==2.0.3
prefix: /usr/local/envs/insanet
